title: Programming prototype
google_analytics:
theme: jekyll-theme-minimal


schedule:

- title: Week 1
  folder: week1/
  url: week1.html
  activities:
  - title: Activity A
    url: activityA.html
  - title: Activity B
    url: activityB.html    
  - title: Activity C
    url: activityC.html    
  - title: Midterm 2023
    url: midterm2023fall.html

- title: Week 2
  folder: week2/
  url: week2.html
  activities:
  - title: Activity A
    url: activityA.html
  - title: Activity B
    url: activityB.html
  - title: Activity C
    url: activityC.html    
  - title: Activity D
    url: activityD.html        

- title: Week 3
  folder: week3/
  url: week3.html
  activities:
  - title: Activity A
    url: activityA.html
  - title: Activity B
    url: activityB.html    
