title: Programming prototype
google_analytics:
theme: jekyll-theme-minimal

schedule:

- title: Introduction
  folder: week1/
  url: 1_overview.html
  activities:
  - title: Why programming
    url: B_why_programming.html
  - title: Files and folders
    url: E_files_and_folders.html
  - title: Get to know
    url: G_get_to_know.html
  - title: Writing programs
    url: K_writing_programs.html
  - title: Learning_programming
    url: L_learning_programming.html
  - title: This course
    url: M_this_course.html

- title: Assignments, types and operators
  folder: week2/
  url: 2_overview.html
  activities:
  - title: Assignments
    url: A_assignments.html
  - title: Exercise
    url: E_exercise.html

- title: Conditionals
  folder: week3/
  url: 3_overview.html
  activities:
  - title: Conditions quiz
    url: K_conditions_quiz.html

- title: Iterations
  folder: week4/
  url: 4_overview.html
  activities:
  - title: Activity A
    url: activityA.html

- title: Functions
  folder: week5/
  url: 5_overview.html
  activities:
  - title: Activity A
    url: activityA.html

- title: Strings
  folder: week6/
  url: 6_overview.html
  activities:
  - title: Activity A
    url: activityA.html

- title: Lists
  folder: week7/
  url: 7_overview.html
  
- title: Dictionaries
  folder: week8/
  url: 8_overview.html
  
- title: Tuples
  folder: week9/
  url: 9_overview.html

- title: Files and IO
  folder: week10/
  url: 10_overview.html

- title: Basic OOP
  folder: week11/
  url: 11_overview.html

- title: Modules and librearies
  folder: week12/
  url: 12_overview.html

- title: Numpy and matplotlib
  folder: week13/
  url: 13_overview.html

