title: Programming prototype
google_analytics:
theme: jekyll-theme-minimal

schedule:

- title: Introduction to ...
  folder: week1/
  url: 1_overview.html
  activities:
  - title: Why ..?
    url: B_why_programming.html
  - title: Files, folders ...
    url: E_files_and_folders.html
  - title: Get to know ...
    url: G_get_to_know.html
  - title: Writing ...
    url: K_writing_programs.html
  - title: How to ..?
    url: L_learning_programming.html
  - title: This course ...
    url: M_this_course.html

- title: Assignments ...
  folder: week2/
  url: 2_overview.html
  activities:
  - title: Assignments
    url: A_assignments.html
  - title: Exercise
    url: E_exercise.html

- title: Conditionals
  folder: week3/
  url: 3_overview.html
  activities:
  - title: Quiz
    url: K_conditions_quiz.html

- title: Iterations
  folder: week4/
  url: 4_overview.html
  activities:
  - title: Quiz
    url: K_loops_quiz.html

- title: Functions
  folder: week5/
  url: 5_overview.html
  activities:
  - title: Activity A
    url: activityA.html

- title: Strings
  folder: week6/
  url: 6_overview.html
  activities:
  - title: Activity A
    url: activityA.html

- title: Lists
  folder: week7/
  url: 7_overview.html
  activities:
  - title: Lists
    url: G_lists.html
  - title: Quiz
    url: K_lists_quiz.html
  
- title: Dictionaries
  folder: week8/
  url: 8_overview.html
  
- title: Tuples
  folder: week9/
  url: 9_overview.html

- title: Files and IO
  folder: week10/
  url: 10_overview.html
  activities:
  - title: Miniproject
    url: P flatten_photos.html

- title: Basic OOP
  folder: week11/
  url: 11_overview.html

- title: Modules ...
  folder: week12/
  url: 12_overview.html

- title: Numpy ...
  folder: week13/
  url: 13_overview.html

